/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardSettingRouteImport } from './routes/dashboard/setting'
import { Route as DashboardRegistrationRouteImport } from './routes/dashboard/registration'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardEventListRouteImport } from './routes/dashboard/event-list'
import { Route as DashboardEditEventRouteImport } from './routes/dashboard/edit-event'
import { Route as DashboardAddEventRouteImport } from './routes/dashboard/add-event'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingRoute = DashboardSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationRoute = DashboardRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventListRoute = DashboardEventListRouteImport.update({
  id: '/event-list',
  path: '/event-list',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditEventRoute = DashboardEditEventRouteImport.update({
  id: '/edit-event',
  path: '/edit-event',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddEventRoute = DashboardAddEventRouteImport.update({
  id: '/add-event',
  path: '/add-event',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/add-event': typeof DashboardAddEventRoute
  '/dashboard/edit-event': typeof DashboardEditEventRoute
  '/dashboard/event-list': typeof DashboardEventListRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/registration': typeof DashboardRegistrationRoute
  '/dashboard/setting': typeof DashboardSettingRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/add-event': typeof DashboardAddEventRoute
  '/dashboard/edit-event': typeof DashboardEditEventRoute
  '/dashboard/event-list': typeof DashboardEventListRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/registration': typeof DashboardRegistrationRoute
  '/dashboard/setting': typeof DashboardSettingRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/add-event': typeof DashboardAddEventRoute
  '/dashboard/edit-event': typeof DashboardEditEventRoute
  '/dashboard/event-list': typeof DashboardEventListRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/registration': typeof DashboardRegistrationRoute
  '/dashboard/setting': typeof DashboardSettingRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/signup'
    | '/dashboard/add-event'
    | '/dashboard/edit-event'
    | '/dashboard/event-list'
    | '/dashboard/projects'
    | '/dashboard/registration'
    | '/dashboard/setting'
    | '/dashboard/team'
    | '/events/$eventId'
    | '/dashboard/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard/add-event'
    | '/dashboard/edit-event'
    | '/dashboard/event-list'
    | '/dashboard/projects'
    | '/dashboard/registration'
    | '/dashboard/setting'
    | '/dashboard/team'
    | '/events/$eventId'
    | '/dashboard'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/signup'
    | '/dashboard/add-event'
    | '/dashboard/edit-event'
    | '/dashboard/event-list'
    | '/dashboard/projects'
    | '/dashboard/registration'
    | '/dashboard/setting'
    | '/dashboard/team'
    | '/events/$eventId'
    | '/dashboard/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/setting': {
      id: '/dashboard/setting'
      path: '/setting'
      fullPath: '/dashboard/setting'
      preLoaderRoute: typeof DashboardSettingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registration': {
      id: '/dashboard/registration'
      path: '/registration'
      fullPath: '/dashboard/registration'
      preLoaderRoute: typeof DashboardRegistrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/event-list': {
      id: '/dashboard/event-list'
      path: '/event-list'
      fullPath: '/dashboard/event-list'
      preLoaderRoute: typeof DashboardEventListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit-event': {
      id: '/dashboard/edit-event'
      path: '/edit-event'
      fullPath: '/dashboard/edit-event'
      preLoaderRoute: typeof DashboardEditEventRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/add-event': {
      id: '/dashboard/add-event'
      path: '/add-event'
      fullPath: '/dashboard/add-event'
      preLoaderRoute: typeof DashboardAddEventRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddEventRoute: typeof DashboardAddEventRoute
  DashboardEditEventRoute: typeof DashboardEditEventRoute
  DashboardEventListRoute: typeof DashboardEventListRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRegistrationRoute: typeof DashboardRegistrationRoute
  DashboardSettingRoute: typeof DashboardSettingRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddEventRoute: DashboardAddEventRoute,
  DashboardEditEventRoute: DashboardEditEventRoute,
  DashboardEventListRoute: DashboardEventListRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRegistrationRoute: DashboardRegistrationRoute,
  DashboardSettingRoute: DashboardSettingRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
